// create-tez-dapp/templates/svelte-js/src/lib/ConnectWalletComponent.svelte
<!-- ConnectWallet.svelte -->
<script>
    import { createEventDispatcher } from 'svelte';
    import { BeaconWallet } from "@taquito/beacon-wallet";
    import { TezosToolkit } from "@taquito/taquito";
    import { NetworkType } from "@airgap/beacon-types";

    const dispatch = createEventDispatcher();
  
    export let rpcUrl; // Receive rpcUrl as a prop
    export let networkType; // Receive rpcUrl as a prop

    const Tezos = new TezosToolkit(rpcUrl); // Use the received rpcUrl

    let wallet;
    let address;
    let balance; 

    async function connectWallet() {
        const newWallet = new BeaconWallet({
          name: "Tezos dApp Boilerplate",
          network: {
           type: networkType,
          },
        });
      await newWallet.requestPermissions();
      address = await newWallet.getPKH();
      getWalletBalance(address);
      wallet = newWallet;

    dispatch('walletConnected', { address, newWallet });
}
  
    function disconnectWallet() {
      wallet.client.clearActiveAccount();
      wallet = undefined;

      dispatch('disconnected');
    }

    const getWalletBalance = async (walletAddress) => {
     const balanceMutez = await Tezos.tz.getBalance(walletAddress);
     balance = balanceMutez.div(1000000).toFormat(2);
  };
  </script>
  
  <main>
    <div class="card">
        {#if wallet}
        <button class="walletButton" on:click={disconnectWallet}>Disconnect wallet</button>
      {:else}
        <button class="walletButton" on:click={connectWallet}>Connect wallet</button>
      {/if}
    </div>
  </main>
  
  <style>
    /* Add your styles here */    
  </style>

// create-tez-dapp/templates/react-ts/src/components/ConnectWalletComponent.tsx
import React from "react";
import { BeaconWallet } from "@taquito/beacon-wallet";
import { NetworkType } from "@airgap/beacon-types";

export default function ConnectWalletButton(props: {
  wallet: BeaconWallet | undefined;
  setWallet: React.Dispatch<React.SetStateAction<BeaconWallet | undefined>>;
  setAddress: React.Dispatch<React.SetStateAction<string | undefined>>;
  networkType: NetworkType;
}) {
  async function connectWallet() {
    console.log("Connectign");
    const newWallet = new BeaconWallet({
      name: "Tezos dApp Boilerplate",
      network: {
        type: props.networkType,
      },
    });
    await newWallet.requestPermissions();
    const address = await newWallet.getPKH();

    props.setAddress(address);
    props.setWallet(newWallet);
  }

  function disconnectWallet() {
    if (props.wallet) {
      props.wallet.client.clearActiveAccount();

      props.setWallet(undefined);
      props.setAddress(undefined);
    }
  }

  return (
    <div className="card">
      {props.wallet ? (
        <button className="walletButton" onClick={disconnectWallet}>
          Disconnect wallet
        </button>
      ) : (
        <button className="walletButton" onClick={connectWallet}>
          Connect wallet
        </button>
      )}
    </div>
  );
}
