// create-tez-dapp/templates/react-js/src/components/ConnectWalletComponent.jsx
import { BeaconWallet } from "@taquito/beacon-wallet";
import { NetworkType } from "@airgap/beacon-types";
import PropTypes from "prop-types";

export default function ConnectWalletButton({
  wallet,
  setWallet,
  setAddress,
  networkType,
}) {
  async function connectWallet() {
    console.log("Connectign");
    const newWallet = new BeaconWallet({
      name: "Tezos dApp Boilerplate",
      network: {
        type: networkType,
      },
    });
    await newWallet.requestPermissions();
    const address = await newWallet.getPKH();

    setAddress(address);
    setWallet(newWallet);
  }

  function disconnectWallet() {
    if (wallet) {
      wallet.client.clearActiveAccount();

      setWallet(undefined);
      setAddress(undefined);
    }
  }

  return (
    <div className="card">
      {wallet ? (
        <button className="walletButton" onClick={disconnectWallet}>
          Disconnect wallet
        </button>
      ) : (
        <button className="walletButton" onClick={connectWallet}>
          Connect wallet
        </button>
      )}
    </div>
  );
}

ConnectWalletButton.propTypes = {
  wallet: PropTypes.string.isRequired,
  setWallet: PropTypes.func,
  setAddress: PropTypes.func,
  networkType: PropTypes.oneOfType(NetworkType),
};

// create-tez-dapp/templates/svelte-js/src/lib/ConnectWalletComponent.svelte
<!-- ConnectWallet.svelte -->
<script>
    import { createEventDispatcher } from 'svelte';
    import { BeaconWallet } from "@taquito/beacon-wallet";
    import { TezosToolkit } from "@taquito/taquito";
    import { NetworkType } from "@airgap/beacon-types";

    const dispatch = createEventDispatcher();
  
    export let rpcUrl; // Receive rpcUrl as a prop
    export let networkType; // Receive rpcUrl as a prop

    const Tezos = new TezosToolkit(rpcUrl); // Use the received rpcUrl

    let wallet;
    let address;
    let balance; 

    async function connectWallet() {
        const newWallet = new BeaconWallet({
          name: "Tezos dApp Boilerplate",
          network: {
           type: networkType,
          },
        });
      await newWallet.requestPermissions();
      address = await newWallet.getPKH();
      getWalletBalance(address);
      wallet = newWallet;

    dispatch('walletConnected', { address, newWallet });
}
  
    function disconnectWallet() {
      wallet.client.clearActiveAccount();
      wallet = undefined;

      dispatch('disconnected');
    }

    const getWalletBalance = async (walletAddress) => {
     const balanceMutez = await Tezos.tz.getBalance(walletAddress);
     balance = balanceMutez.div(1000000).toFormat(2);
  };
  </script>
  
  <main>
    <div class="card">
        {#if wallet}
        <button class="walletButton" on:click={disconnectWallet}>Disconnect wallet</button>
      {:else}
        <button class="walletButton" on:click={connectWallet}>Connect wallet</button>
      {/if}
    </div>
  </main>
  
  <style>
    /* Add your styles here */    
  </style>
