// tezos-verify/src/components/connectWallet.tsx
"use client";
// import { BeaconWallet } from "@taquito/beacon-wallet";
// import { TezosToolkit } from "@taquito/taquito";
// import { NetworkType } from "@airgap/beacon-types";
import useUserWalletStore from "~/zustand/useUserWalletStore";
import useUserAddressStore from "~/zustand/useUserAddressStore";

export function ConnectWalletButton() {
  const { setUserWallet } = useUserWalletStore();

  const { setUserAddress } = useUserAddressStore();

  async function connectWallet() {
    console.log("Connectign");
    const newWallet = new (await import("@taquito/beacon-wallet")).BeaconWallet(
      {
        name: "Tezos dApp Boilerplate",
        network: {
          type: (await import("@airgap/beacon-types")).NetworkType.MAINNET,
        },
      },
    );
    await newWallet.requestPermissions();

    const address = await newWallet.getPKH();

    const beaconID = await newWallet.client.beaconId;

    console.log(beaconID);

    setUserWallet(newWallet);

    setUserAddress(address);

    console.log(address);
  }

  return (
    <button
      className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
      onClick={connectWallet}
    >
      Connect Wallet
    </button>
  );
}

export function DisconnectWalletButton() {
  const { resetUserWallet, userWallet } = useUserWalletStore();

  const { resetUserAddress } = useUserAddressStore();

  async function disconnectWallet() {
    if (userWallet) {
      await userWallet.client.clearActiveAccount();

      resetUserWallet();
      resetUserAddress();
    }
  }

  return (
    <button
      className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
      onClick={disconnectWallet}
    >
      Disconnect
    </button>
  );
}

// create-tez-dapp/templates/svelte-js/src/lib/ConnectWalletComponent.svelte
<!-- ConnectWallet.svelte -->
<script>
    import { createEventDispatcher } from 'svelte';
    import { BeaconWallet } from "@taquito/beacon-wallet";
    import { TezosToolkit } from "@taquito/taquito";
    import { NetworkType } from "@airgap/beacon-types";

    const dispatch = createEventDispatcher();
  
    export let rpcUrl; // Receive rpcUrl as a prop
    export let networkType; // Receive rpcUrl as a prop

    const Tezos = new TezosToolkit(rpcUrl); // Use the received rpcUrl

    let wallet;
    let address;
    let balance; 

    async function connectWallet() {
        const newWallet = new BeaconWallet({
          name: "Tezos dApp Boilerplate",
          network: {
           type: networkType,
          },
        });
      await newWallet.requestPermissions();
      address = await newWallet.getPKH();
      getWalletBalance(address);
      wallet = newWallet;

    dispatch('walletConnected', { address, newWallet });
}
  
    function disconnectWallet() {
      wallet.client.clearActiveAccount();
      wallet = undefined;

      dispatch('disconnected');
    }

    const getWalletBalance = async (walletAddress) => {
     const balanceMutez = await Tezos.tz.getBalance(walletAddress);
     balance = balanceMutez.div(1000000).toFormat(2);
  };
  </script>
  
  <main>
    <div class="card">
        {#if wallet}
        <button class="walletButton" on:click={disconnectWallet}>Disconnect wallet</button>
      {:else}
        <button class="walletButton" on:click={connectWallet}>Connect wallet</button>
      {/if}
    </div>
  </main>
  
  <style>
    /* Add your styles here */    
  </style>
